subscriber:
  cloud_topic_name: /velodyne_points
  imu_topic_name: /imu/data_updated
  lo_topic_name: /aft_mapped_to_init # lidar odometry
  wo_topic_name: /husky_velocity_controller/odom # wheel odometry
publisher:
  cloud_adjusted_topic_name: /velodyne_points_adjusted
  pose_topic_name: /nav_filter/nav_filter/states
  cloud_frame_id: /velodyne
  base_frame_id: map
  child_frame_id: base_link
scan_adjust:
  distortion_adjust_method: IMU
  do_distortion: false

